<?php

use Illuminate\Database\Seeder;

class Agrupacion2Seeder extends Seeder
{
  
    public function run()
    {
        
         DB::table('cat_agrupacion2')->insert([

                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 1],
                               ['nombre' => 'ARMA BLANCA','idAgrupacion1' => 2],
                               ['nombre' => 'ARMA DE FUEGO','idAgrupacion1' =>2],
                               ['nombre' => 'OTROS','idAgrupacion1' => 2],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 3],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 4],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 5],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 6],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 7],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 8],
                               ['nombre' => 'VECINAL A VEHICULO','idAgrupacion1' =>9],
                               ['nombre' => 'VECINAL A CAMION REPARTIDOR','idAgrupacion1'=> 9],
                               ['nombre' => 'VECINAL A TRANSEUNTE','idAgrupacion1' => 9],
                               ['nombre' => 'DE PASAJEROS','idAgrupacion1' => 10],
                               ['nombre' => 'A CAMION REPARTIDOR','idAgrupacion1' =>11],
                               ['nombre' => 'A TRANSEUNTE','idAgrupacion1' => 11],
                               ['nombre' => 'A VEHICULO','idAgrupacion1' =>11],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 12],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 13],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 14],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 15],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 16],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 17],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 18],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 19],
                               ['nombre' => 'EDUCATIVO','idAgrupacion1' =>20],
                               ['nombre' => 'FAMILIAR','idAgrupacion1' => 20],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 21],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 22],
                               ['nombre' => 'LA PRESERVACION DEL LUGAR DE LOS HECHOS','idAgrupacion1' =>23],
                               ['nombre' => 'LA SALUD','idAgrupacion1' => 23],
                               ['nombre' => 'EL ESTADO CIVIL','idAgrupacion1' => 23],
                               ['nombre' => 'EL RESPETO A LOS MUERTOS','idAgrupacion1' => 23],
                               ['nombre' => 'LA FILIACION','idAgrupacion1' =>23],
                               ['nombre' => 'LA SEGURIDAD DEL TRANSITO DE VEHICULOS','idAgrupacion1' =>23],
                               ['nombre' => 'LA SEGURIDAD VIAL Y LOS MEDIOS DE TRANSPORTE','idAgrupacion1' =>23],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 24],
                               ['nombre' => 'ACTOS DE MALTRATO O CRUELDAD EN CONTRA DE LOS ANIMALES','idAgrupacion1' => 25],
                               ['nombre' => 'MEDICOS, AUXILIARES Y OTROS RELACIONADOS CON LA PRACTICA DE LA MEDICINA','idAgrupacion1' => 25],
                               ['nombre' => 'OTROS PROFESIONALES Y TECNICOS','idAgrupacion1' =>25],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 26],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 27],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 28],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 29],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 30],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 31],
                               
                               ['nombre' => 'CON VIOLENCIA','idAgrupacion1' => 32],
                               ['nombre' => 'SIN VIOLENCIA','idAgrupacion1' => 32],
                               ['nombre' => 'CON VIOLENCIA CAMINO VECINAL','idAgrupacion1' => 33],
                               ['nombre' => 'CON VIOLENCIA CARRETERA','idAgrupacion1' => 33],
                               ['nombre' => 'CON VIOLENCIA ZONA URBANA','idAgrupacion1' => 33],
                               ['nombre' => 'SIN VIOLENCIA CAMINO VECINAL','idAgrupacion1' => 33],
                               ['nombre' => 'SIN VIOLENCIA CARRETERA','idAgrupacion1' => 33],
                               ['nombre' => 'SIN VIOLENCIA ZONA URBANA','idAgrupacion1' => 33],
                               ['nombre' => 'CON VIOLENCIA','idAgrupacion1' => 34],
                               ['nombre' => 'CON VIOLENCIA','idAgrupacion1' => 35],
                               ['nombre' => 'SIN VIOLENCIA','idAgrupacion1' => 35],
                               ['nombre' => 'CON VIOLENCIA CAMINO VECINAL','idAgrupacion1' => 36],
                               ['nombre' => 'CON VIOLENCIA CARRETERA','idAgrupacion1' => 36],
                               ['nombre' => 'SIN VIOLENCIA CAMINO VECINAL','idAgrupacion1' => 36],
                               ['nombre' => 'SIN VIOLENCIA CARRETERA','idAgrupacion1' => 36],
                               ['nombre' => 'EN ESPACIO ABIERTO AL PUBLICO CON VIOLENCIA','idAgrupacion1' => 36],
                               ['nombre' => 'EN ESPACIO ABIERTO AL PUBLICO SIN VIOLENCIA','idAgrupacion1' => 36],
                               ['nombre' => 'CON VIOLENCIA ZONA URBANA','idAgrupacion1' => 37],
                               ['nombre' => 'SIN VIOLENCIA ZONA URBANA','idAgrupacion1' => 37],
                               ['nombre' => 'CON VIOLENCIA','idAgrupacion1' => 38],
                               ['nombre' => 'SIN VIOLENCIA','idAgrupacion1' => 38],
                               ['nombre' => 'CON VIOLENCIA CAMINO VECINAL','idAgrupacion1' => 39],
                               ['nombre' => 'CON VIOLENCIA CARRETERA','idAgrupacion1' => 39],
                               ['nombre' => 'CON VIOLENCIA ZONA URBANA','idAgrupacion1' => 39],
                               ['nombre' => 'SIN VIOLENCIA CAMINO VECINAL','idAgrupacion1' => 39],
                               ['nombre' => 'SIN VIOLENCIA CARRETERA','idAgrupacion1' => 39],
                               ['nombre' => 'SIN VIOLENCIA ZONA URBANA','idAgrupacion1' => 39],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 40],
                               ['nombre' => 'A INTERIOR DE VEHICULO CON VIOLENCIA','idAgrupacion1' => 41],
                               ['nombre' => 'A INTERIOR DE VEHICULO SIN VIOLENCIA','idAgrupacion1' => 41],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 42],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 43],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 44],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 45],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 46],
                               
                               ['nombre' => '(CABLES, TUBOS y OTROS OBJETOS DESTINADOS AL SERVICIO PUBLICO) SIN VIOLENCIA','idAgrupacion1' => 47],
                               ['nombre' => '(CABLES, TUBOS y OTROS OBJETOS DESTINADOS AL SERVICIO PUBLICO) CON VIOLENCIA','idAgrupacion1' => 47],
                               ['nombre' => '(TRACTORES) SIN VIOLENCIA','idAgrupacion1' => 47],
                               ['nombre' => '(TRACTORES) CON VIOLENCIA','idAgrupacion1' => 47],
                               ['nombre' => '(HERRAMIENTA INDUSTRIAL O AGRICOLA) SIN VIOLENCIA','idAgrupacion1' => 47],
                               ['nombre' => '(HERRAMIENTA INDUSTRIAL O AGRICOLA) CON VIOLENCIA','idAgrupacion1' => 47],
                               
                               ['nombre' => '(EMBARCACIONES PEQUEÑAS Y GRANDES) SIN VIOLENCIA','idAgrupacion1' => 48],
                               ['nombre' => '(EMBARCACIONES PEQUEÑAS Y GRANDES) CON VIOLENCIA','idAgrupacion1' => 48],
                               ['nombre' => '(MOTOCICLETA) SIN VIOLENCIA','idAgrupacion1' => 48],
                               ['nombre' => '(MOTOCICLETA) CON VIOLENCIA','idAgrupacion1' => 48],
                               ['nombre' => 'CON VIOLENCIA','idAgrupacion1' => 49],
                               ['nombre' => 'SIN VIOLENCIA','idAgrupacion1' => 49],
                               ['nombre' => 'CON VIOLENCIA','idAgrupacion1' => 50],
                               ['nombre' => 'SIN VIOLENCIA','idAgrupacion1' => 50],
                               
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 51],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 52],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 53],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 54],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 55],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 56],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 57],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 58],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 59],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 60],  
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 61],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 62],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 63],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 64],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 65],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 66],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 67],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 68],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' =>69],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 70],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 71],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' =>72],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 73],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 74],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 75],
                               
                               
                               
                               ['nombre' => 'ARMA BLANCA','idAgrupacion1' => 76],
                               ['nombre' => 'ARMA DE FUEGO','idAgrupacion1' => 76],
                               ['nombre' => 'OTROS','idAgrupacion1' => 76],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 77],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 78],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 79],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 80],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 81],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 82],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 83],
                               
                               ['nombre' => 'AL SUICIDIO EN GRADO DE TENTATIVA','idAgrupacion1' => 84],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 85],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 86],
                               ['nombre' => 'A ATROPELLADOS','idAgrupacion1' =>87],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 88],
                               ['nombre' => 'FISICA','idAgrupacion1' => 89],
                               ['nombre' => 'EN GRADO DE TENTATIVA','idAgrupacion1' => 89],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 90],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 91],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 92],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 93],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 94],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 95],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 96],
                               ['nombre' => 'EN GRADO DE TENTATIVA','idAgrupacion1' => 97],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 98],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 99],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 100],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 101],
                               ['nombre' => 'SIN AGRUPACION','idAgrupacion1' => 102],
                               ['nombre' => 'EN GRADO DE TENTATIVA','idAgrupacion1' => 103],
                               ['nombre' => 'EN GRADO DE TENTATIVA','idAgrupacion1' => 104],
                               ['nombre' => 'EN GRADO DE TENTATIVA','idAgrupacion1' => 105],
                               ['nombre' => 'EN GRADO DE TENTATIVA','idAgrupacion1' => 106],
                               ['nombre' => 'EN GRADO DE TENTATIVA','idAgrupacion1' => 107],
                               ['nombre' => 'EN GRADO DE TENTATIVA','idAgrupacion1' => 108],
                               ['nombre' => 'EN GRADO DE TENTATIVA','idAgrupacion1' => 109],
                               ['nombre' => 'EN GRADO DE TENTATIVA','idAgrupacion1' => 110],
                               ['nombre' => 'EN GRADO DE TENTATIVA','idAgrupacion1' => 111],
                               
                               
                               ['nombre' => 'AGRAVADA','idAgrupacion1' => 112],
                               ['nombre' => 'AGRAVADA','idAgrupacion1' => 113],
                               ['nombre' => 'EN GRADO DE TENTATIVA','idAgrupacion1' => 115]
                               
                               ]);
                               }
                               }
