<?php

use Illuminate\Database\Seeder;

class Agrupacion1Seeder extends Seeder
{    /**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{

		   DB::table('cat_agrupacion1')->insert([

				
				['nombre' => 'CULPOSAS', 'idCatDelito' => 1], 
				['nombre' => 'DOLOSAS', 'idCatDelito' => 1],
				['nombre' => 'EN GRADO DE TENTATIVA', 'idCatDelito' => 2],
				['nombre' => 'A PIPA', 'idCatDelito' => 2], 
				['nombre' => 'A TRAILER', 'idCatDelito' => 2],
				['nombre' => 'A TAXI', 'idCatDelito' => 2],
				['nombre' => 'A PARTICULAR', 'idCatDelito' => 2],
				['nombre' => 'A OTROS', 'idCatDelito' => 2],
				['nombre' => 'EN CAMINO', 'idCatDelito' =>2],
				['nombre' => 'A CAMION', 'idCatDelito' => 2],
				['nombre' => 'EN CARRETERA', 'idCatDelito' =>2],
				['nombre' => 'EN GRADO DE TENTATIVA', 'idCatDelito' =>2],
				['nombre' => 'OTROS ASALTOS', 'idCatDelito' => 2],
				['nombre' => 'FISICA', 'idCatDelito' =>3],
				['nombre' => 'PSICOLOGICA', 'idCatDelito' =>3],
				['nombre' => 'ECONOMICA O PATRIMONIAL', 'idCatDelito' => 3],
				['nombre' => 'OBSTETRICA', 'idCatDelito' =>3],
				['nombre' => 'INSTITUCIONAL', 'idCatDelito' =>3],
				['nombre' => 'LABORAL', 'idCatDelito' => 3], 
				['nombre' => 'EN EL AMBITO', 'idCatDelito' => 3],
				['nombre' => 'TERRENO AGRICOLA O GANADERO', 'idCatDelito' =>4],
				['nombre' => 'DE LOS SERVIDORES PUBLICOS ART. 8', 'idCatDelito' =>5],
				['nombre' => 'CONTRA', 'idCatDelito' =>5],
				['nombre' => 'AMBIENTALES', 'idCatDelito' => 5],   
				['nombre' => 'COMETIDOS POR', 'idCatDelito' =>5],
				['nombre' => 'DE ABOGADOS, DEFENSORES Y LITIGANTES', 'idCatDelito' => 5],
				['nombre' => 'INFORMATICOS', 'idCatDelito' =>5],
				['nombre' => 'ELECTORALES', 'idCatDelito' => 5], 
				['nombre' => 'NO CONSTITUTIVOS DE DELITO', 'idCatDelito' => 6],
				['nombre' => 'DELICTUOSOS NO ESPECIFICADOS', 'idCatDelito' => 6],
				['nombre' => 'OTROS', 'idCatDelito' => 9],
				['nombre' => 'BANCO','idCatDelito'=> 9],
				['nombre' => 'CAMION REPARTIDOR', 'idCatDelito' => 9],
				['nombre' => 'CASA HABITACION', 'idCatDelito' => 9],
				['nombre' => 'NEGOCIACIONES', 'idCatDelito' => 9],
				['nombre' => 'TRANSEUNTE', 'idCatDelito' => 9],
				['nombre' => 'TRANSEUNTES', 'idCatDelito' => 9], 
				['nombre' => 'FRUTOS', 'idCatDelito' => 9], 
				['nombre' => 'VEHICULO', 'idCatDelito' => 9],
				['nombre' => 'GRADO DE TENTATIVA', 'idCatDelito' =>9],
				['nombre' => 'DE OBJETOS', 'idCatDelito' =>9],
				['nombre' => 'CALIFICADO', 'idCatDelito' => 9],
				['nombre' => 'FLUIDO', 'idCatDelito' => 9],
				['nombre' => 'AGRAVADO', 'idCatDelito' =>9],
				['nombre' => 'ESPECIFICO', 'idCatDelito' => 9],
				['nombre' => 'GENERICO', 'idCatDelito' => 9],
				['nombre' => 'MAQUINARIA', 'idCatDelito' =>9], 
				['nombre' => 'VEHICULO AUTOMOTOR', 'idCatDelito' => 9],
				['nombre' => 'TRANSPORTISTAS', 'idCatDelito' => 9],  
				['nombre' => 'AUTOPARTES', 'idCatDelito' =>9],
				['nombre' => 'DE FAMILIARES', 'idCatDelito' => 10],
				['nombre' => 'EN GRADO DE TENTATIVA', 'idCatDelito' => 11],
				['nombre' => 'DE CONFIANZA', 'idCatDelito' => 13],
				['nombre' => 'EROTICO-SEXUAL', 'idCatDelito' =>13],
				['nombre' => 'DESHONESTOS', 'idCatDelito' => 13],
				['nombre' => 'DE AUTORIDAD', 'idCatDelito' =>13],
				['nombre' => 'FRAUDULENTA', 'idCatDelito' => 14],
				['nombre' => 'A LA LIBERTAD DE REUNION Y EXPRESION', 'idCatDelito' =>14],
				['nombre' => 'DE MORADA', 'idCatDelito' => 15],
				['nombre' => 'DE DESPACHO, OFICINA O CONSULTORIO', 'idCatDelito' => 15],
				['nombre' => 'A LA LIBERTAD DE REUNION Y EXPRESION', 'idCatDelito' => 17],
				['nombre' => 'EN GRADO DE TENTATIVA', 'idCatDelito' =>22],
				['nombre' => 'DE MENORES O INCAPACES', 'idCatDelito' =>25],
				['nombre' => 'CULPOSOS', 'idCatDelito' =>26],
				['nombre' => 'DOLOSOS', 'idCatDelito' => 26],
				['nombre' => 'DE PERSONAS', 'idCatDelito' =>27],
				['nombre' => 'FORZADA DE PERSONAS', 'idCatDelito' =>27],
				['nombre' => 'POR FAVORECIMIENTO', 'idCatDelito' =>30],
				['nombre' => 'POR RECEPTACION', 'idCatDelito' => 30],
				['nombre' => 'EN GRADO DE TENTATIVA', 'idCatDelito' =>36],
				['nombre' => 'DE DOCUMENTOS', 'idCatDelito' =>39],
				['nombre' => 'DE SELLOS, LLAVES, MARCAS Y CONTRASEÑAS', 'idCatDelito' => 39],
				['nombre' => 'DE TITULOS Y CONTRA LA FE PUBLICA', 'idCatDelito' =>39],
				['nombre' => 'PROCESAL', 'idCatDelito' => 41],
				['nombre' => 'EN GRADO DE TENTATIVA', 'idCatDelito' =>41],
				['nombre' => 'DOLOSO', 'idCatDelito' => 42],
				['nombre' => 'CULPOSO', 'idCatDelito' => 42],
				['nombre' => 'EN GRADO DE TENTATIVA', 'idCatDelito' =>42],
				['nombre' => 'POR ACCIDENTE DE TRANSITO', 'idCatDelito' => 42],
				['nombre' => 'CALIFICADO', 'idCatDelito' => 42],
				['nombre' => 'EN RIÑA', 'idCatDelito' => 42],
				['nombre' => 'DE LA OBLIGACION DE DAR ALIMENTOS', 'idCatDelito' =>43],
				['nombre' => 'DE UN DEBER LEGAL', 'idCatDelito' => 43],
				['nombre' => 'O AYUDA AL SUICIDIO', 'idCatDelito' =>45] ,
				['nombre' => 'INDUCCION A LA MENDICIDAD', 'idCatDelito' => 45],
				['nombre' => 'A MENORES', 'idCatDelito' => 48],
				['nombre' => 'DE AUXILIO', 'idCatDelito' => 51],
				['nombre' => 'DE CUIDADO', 'idCatDelito' => 51],
				['nombre' => 'DE LA LIBERTAD', 'idCatDelito' =>56],
				['nombre' => 'A COMETER UN DELITO APOLOGIA DE ESTE O DE ALGUN VICIO', 'idCatDelito' =>57],
				['nombre' => 'DE LA SANCION DE PRIVACION, SUSPENSION O INHABILITACION DE DERECHOS', 'idCatDelito' =>58],
				['nombre' => 'DE SELLOS', 'idCatDelito' =>58],
				['nombre' => 'DE SECRETOS', 'idCatDelito' =>60],
				['nombre' => 'DE INFORMACION RESERVADA', 'idCatDelito' =>60],
				['nombre' => 'EN GRADO DE TENTATIVA', 'idCatDelito' =>62],
				['nombre' => 'EXPRESS', 'idCatDelito' =>62],
				['nombre' => 'AGRAVADO', 'idCatDelito' =>62],
				['nombre' => 'DE MENORES O INCAPACES', 'idCatDelito' =>66],
				['nombre' => 'DE INFLUENCIA', 'idCatDelito' =>68],
				['nombre' => 'DE MENORES', 'idCatDelito' =>68],
				['nombre' => 'A LA AUTORIDAD', 'idCatDelito' =>69],
				['nombre' => 'A LA MORAL PUBLICA', 'idCatDelito' =>69],
				['nombre' => 'DE FUNCIONES', 'idCatDelito' =>72],
				['nombre' => 'DE PROFESION', 'idCatDelito' =>72],
				['nombre' => 'DE CORRESPONDENCIA', 'idCatDelito' =>76],
				['nombre' => 'DE LAS LEYES SOBRE INHUMACIONES Y EXHUMACIONES', 'idCatDelito' => 76],
				['nombre' => 'EN GRADO DE TENTATIVA', 'idCatDelito' => 76],
				['nombre' => 'ENTRE PARIENTES', 'idCatDelito' => 76],
				['nombre' => 'POR EQUIPARACION', 'idCatDelito' => 76],
				['nombre' => 'TUMULTUARIA', 'idCatDelito' => 76],
				['nombre' => 'DE LA INTIMIDAD PERSONAL', 'idCatDelito' => 76],
				['nombre' => 'ESPECIFICA', 'idCatDelito' =>76],
				['nombre' => 'GENERICA', 'idCatDelito' => 76],
				['nombre' => 'INDEBIDA DE COSA MUEBLE', 'idCatDelito' =>80],
				['nombre' => 'DE MENORES', 'idCatDelito' => 80],
				['nombre' => 'INFANTIL O DE INCAPACES', 'idCatDelito' => 83],
				['nombre' => 'AGRAVADA', 'idCatDelito' => 84],
				['nombre' => '1er PARRAFO', 'idCatDelito' => 84],
				['nombre' => 'EN GRADO DE TENTATIVA', 'idCatDelito' =>84],
				['nombre' => '2do PARRAFO', 'idCatDelito' =>84],
				['nombre' => 'EN GRADO DE TENTATIVA', 'idCatDelito' =>86]
			]);
		}
}

